//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFClinic
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class cza
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cza()
        {
            this.wizyties = new ObservableCollection<wizyty>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> dataprzyjecia { get; set; }
        public Nullable<System.DateTime> godzinaprzyjecia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<wizyty> wizyties { get; set; }
    }
}
