//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFClinic
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class recepta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public recepta()
        {
            this.chorobas = new ObservableCollection<choroba>();
        }
    
        public int ID { get; set; }
        public string leki { get; set; }
        public Nullable<int> ilosc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<choroba> chorobas { get; set; }
    }
}
