//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFClinic
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class wizyty
    {
        public int ID { get; set; }
        public int pacjent { get; set; }
        public int lekarz { get; set; }
        public int czas { get; set; }
        public int choroba { get; set; }
    
        public virtual choroba choroba1 { get; set; }
        public virtual cza cza { get; set; }
        public virtual lekarz lekarz1 { get; set; }
        public virtual pacjent pacjent1 { get; set; }
    }
}
